### ISSUE TITLE
refactor process

### ISSUE THREAD

**Issue by akileez** [akileez/npinit#59]
pages to be rewritten:
- [x] index.js
- [x] app/meta.js
- [x] app/git.js
- [x] app/tmpls.js (was index.js and lib/write.js)
- [x] app/install.js 
- [x] app/display.js (was logger)

other items to be considered:
- [x] handle license files. what am I going to do here? [https://github.com/akileez/npinit/issues/58] keeping status quo at the moment. future feature addition.
- [x] use akileez/toolz (not using. just use individual modules) see [11137d3b9932c33b6fa0bcd269f5863d1e7076d4]
- [x] move templates to lib directory
- [x] check for repo creation errors. see [https://github.com/akileez/npinit/issues/26] fixed [bc16f240778842240db4be0e709f46c763b91a5b]
- [x] logic for addRemote. see [https://github.com/akileez/npinit/issues/44]
- [ ] update documentation. see [https://github.com/akileez/npinit/issues/39]
- [x] change options noRemote and noPush --> remote and push respectively. see [cd61baed0fc75da1dd41f3f3aeae1d7a73c23c28]
- [x] verbose mode to display npm install and git messages. see  [ffc34efb9b31d6354976623e43e1390a792ec8a7] and  [f6084eb928389748dddc519f8f0910d6aee48e47]
- [ ] tag and release. see [https://github.com/akileez/npinit/issues/50]
- [x] update dependencies. [json-colorz] [0c17fe3e32cf0f880749e7cd03dd6fc7242d425b]
- [x] colorized cli for usage display 
- [x] license support for additional files

~~allow git repo to be inited after project setup.~~ see [https://github.com/akileez/npinit/issues/45]
~~allow dependencies to be install after project setup~~
~~allow project to be required within another project~~ see [https://github.com/akileez/npinit/issues/55]

**Comment by akileez** [comment]
need to remove old files as well.

**Comment by akileez** [comment]
app/tmpls.js working fine. need to figure out the license files process completely.

**Comment by akileez** [comment]
process.nextTick solved with re-write of app/tmpls.js. see [https://github.com/akileez/npinit/issues/54]

**Comment by akileez** [comment]
logger solved with creation of app/display.js. see [https://github.com/akileez/npinit/issues/52]

**Comment by akileez** [comment]
mustache replaced with `expand` in app/tmpls.js. see [https://github.com/akileez/npinit/issues/57]

**Comment by akileez** [comment]
prior index.js file moved to app directory (tmpls.js). see [https://github.com/akileez/npinit/issues/56]

**Comment by akileez** [comment]
phase 1 complete. matched functionality with version 0.7 branch. start working on phase 2: option re-config for flexibility.

**Comment by akileez** [comment]
phase 2 complete. re-configed options to use remote (push is auto config). removed addRemote, noRemote and noPush. 

Decided against installing git after the fact. a shell script can take care of this in less key strokes.
Decided against installing dependencies after the fact. npm install is fine and what I do now.
Decided against project being required within another program. although this is now possible, I don't care too much for it. There are probably other projects which do this. I just really need a quick project init.

**Comment by akileez** [comment]
3 features to implement...future reference:
- [x] colorized cli for usage display 
- [ ] git authorization [feature addition -- research needed]
- [x] license support for additional files

**Comment by akileez** [comment]
add verbose option for displaying git and dependencies messages (stderr and stdout)
done with ffc34efb9b31d6354976623e43e1390a792ec8a7

**Comment by akileez** [comment]
phase 3 complete. just documentation, source files (toolz or not) and license support

**Comment by akileez** [comment]
keeping license support as is for now. will revisit in a future update.

**Comment by akileez** [comment]
phase 4 complete. only documentation and code lint remains

**Comment by akileez** [comment]
lint complete

**Comment by akileez** [comment]
reminder to update json-colorz to version 0.2.0 after refactor branch is merged.

**Comment by akileez** [comment]
still working on the usage() documentation. it is a pain at the moment with formatting but I am working on an outside project which should be completed shortly to remedy the situation.

**Comment by akileez** [comment]
finished all the small misc tasks on my mind but didn't document here [check the commits]. Now I can focus solely on README documentation. should be done in two or three days.

**Comment by akileez** [comment]
color command-line display functional but not perfected.
license support added. will expand the number by a few more.
need to finish docs

github authorization to come later.

**Comment by akileez** [comment]
reminder...[https://github.com/akileez/npinit/issues/61]
remove button style

**Comment by akileez** [comment]
merged.[https://github.com/akileez/npinit/commit/5a6fddbb3db2b19bf69a77d898f26854e9cedd2c]
docs need to be finished, buttons on readme, final checks also. been running this for two months in its present form. no major issues. just clean up work to do.
